[package]
name = "grep"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Vivek Tiwari <beeb5k6@gmail.com>"]
repository = "https://github.com/beeb5k/tinygrep"

[dependencies]
