name: Auto Release

on:
  push:
    tags:
      - 'v*'   # Trigger on tags like v0.1.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Get version from Cargo.toml
        id: cargo
        run: |
          version=$(cargo read-manifest | jq -r .version)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v$VERSION"
          name: "v$VERSION"
          body: "Release $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
